### PR TITLE
Add query parameter for MessageFormat.setIntlSupport(true)

### PR DESCRIPTION
**Pull request by jbaudanza**

### CODE REVIEW

**Comment by cletusw** [comment]
Looks great, thanks!

**Comment by cletusw** [comment]
@jbaudanza I'm curious: are you using this with https://github.com/cletusw/multi-json-loader by any chance?

**Comment by cletusw** [comment]
Also, I just published version 0.5.0 to npm with this change.

**Comment by jbaudanza** [comment]
Cool, thanks! I'm just using the regular json loader. I'm only loading two different language files.

**Pull request merged**
